//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_quanlynhahang.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class binhluan
    {
        public int id { get; set; }
        public int iduser { get; set; }
        public DateTime ngaybinhluan { get; set; }
        public string noidung { get; set; }
        public int rate { get; set; }

    }
}
