//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_quanlynhahang.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietgoimon
    {
        public int id { get; set; }
        public int idpgm { get; set; }
        public int idmon { get; set; }
        public int soluong { get; set; }
        public int gia { get; set; }

    }
}
