//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_quanlynhahang.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachthanhtoan
    {
        public int id { get; set; }
        public int idphieu { get; set; }
        public int idkhach { get; set; }
        public int idnv { get; set; }
        public DateTime giott { get; set; }
        public string hinhthuctt { get; set; }
        public int sotien { get; set; }

    }
}
