//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_quanlynhahang.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public int id { get; set; }
        public int idbophan { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public DateTime ngaysinh { get; set; }
        public int gioitinh { get; set; }
        public string diachi { get; set; }
        public DateTime gianhap { get; set; }
        public khachthanhtoan khachthanhtoan { get; set; }
        public bophan bophan { get; set; }
        public List<nvca> nvca { get; set; }
    }
}
